### ISSUE TITLE
Placeholder overlay not disappear sometimes after resize finished

### ISSUE THREAD

**Issue by cetintozkoparan** [bensladden/vue-responsive-dash#101]
If I resize items multiple times sometimes placeholder div could not disappear. Here is an example image;

![image](https://user-images.githubusercontent.com/3630427/78510471-fb6cbe00-779d-11ea-9b50-ce7932fa686c.png)

**Comment by bensladden** [comment]
Thanks for reporting the issue ill have a look into it

**Comment by bensladden** [comment]
Please try new version v0.3.26
