### ISSUE TITLE
Cannot set property id of #<DashItem> which has only a getter

### ISSUE THREAD

**Issue by peterjslater** [bensladden/vue-responsive-dash#116]
Hi
I have started getting the following error when changing layouts dynamically since updating to 0.3.26
Do you have any ideas ? If not, I'll try and replicate the issue in https://codesandbox.io/ so you can have a look, hopefully I will be able to replicate the issue in a simple case.

I get the error when changing from one set of layouts to a completly separate set of layouts at the same breakpoint (screen size). The id's are different so its not a duplicate id issue. The crash caues the debug view not to update, but the error still occurs with debug turned off.

`TypeError: Cannot set property id of #<DashItem> which has only a getter
    at VueComponent.handler (vue-responsive-dash.common.js?e6d2:10032)
    at Watcher.run (vue.runtime.esm.js?2b0e:4568)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:4310)
    at Array.eval (vue.runtime.esm.js?2b0e:1980)
    at flushCallbacks (vue.runtime.esm.js?2b0e:1906)`

**Comment by bensladden** [comment]
If you can setup a repo that always makes it easier for me to see whats going on.

**Comment by bensladden** [comment]
I used another test we did in the past but could not replicate this issue: [https://codesandbox.io/s/vue-responsive-dash-3zorp?file=/src/App.vue]9https://codesandbox.io/s/vue-responsive-dash-3zorp?file=/src/App.vue)

**Comment by peterjslater** [comment]
Hi

I was able to replicate it, I found the cause was using the index as the key
it works with
   <dash-item v-for="item in layout.items" v-bind.sync="item" **:key="item.id"**>
but not with
   <dash-item v-for="(item, index) in layout.items" v-bind.sync="item" **:key="index"**>

Replicated here:
https://codesandbox.io/s/vue-responsive-dash-qd5d3?file=/src/App.vue

Does the key have to be the item.id ?
I think I changed it to index when i was trying to get the drag drop to work.

Thanks
Peter

**Comment by bensladden** [comment]
Hi,

I believe it does need to be item.id otherwise the system **may** not sync back to the array of items in the correct order or change the wrong item. This is why the error occurs as its actually changing the dash items internally.

**Comment by peterjslater** [comment]
ok thanks, i will change it back to id.
