### ISSUE TITLE
[Feature Request] min/max column and row height/width and min/max item height/width

### ISSUE THREAD

**Issue by KBOE2** [bensladden/vue-responsive-dash#118]
So I just found this component today and I really love it. It is simple to use and works pretty well.
But I really miss the option to set a minimum width and height vor Grid fields and also for items.
I am creating a currently nesting grids so that within an Item, there is another grid with just one column but each of the nested items do have same height as width and this is a bit annoying :)

Is this already planned for future and can I look forward to see this feature soon?

Greetings
Jan :)

**Comment by bensladden** [comment]
Hi Jan, 
Thanks for your positive feedback.
Indeed some of these features are inside the core already however i have not exposed them to vue props. To confirm i am on the same page you wish for the following options:

- settable rowHeight instead of always keeping the grid square.
- settable columnWidth instead of it growing or shrinking to fit the area
- limits on column width (min/max) to avoid items getting to small /large (assuming colWidth is not statically set as per dot point 2?

**Comment by KBOE2** [comment]
Correct. These were my ideas.

**Comment by bensladden** [comment]
Hi Jan,
Give the latest version a try. I think its what you are after: [https://vue-responsive-dash.netlify.app/api/#dash-layout](https://vue-responsive-dash.netlify.app/api/#dash-layout)

**Comment by KBOE2** [comment]
It does work partly so far.
I've set a `rowHeight` to 20. That does work for items with height 1: They got a height of 20 px.
But if I resize them to a greater height, heights are 10 px to large. So when an Item uses more than one row, it is 10px to high.

Furthermore I would love to see a min/max colSpan and rowSpan to limit the user in resizing items.

**Comment by KBOE2** [comment]
> It does work partly so far.
I've set a rowHeight to 20. That does work for items with height 1: They got a height of 20 px.
But if I resize them to a greater height, heights are 10 px to large. So when an Item uses more than one row, it is 10px to high.

Just found out that this is caused by the margin set in Layout, so it is not a bug 😇

**Comment by bensladden** [comment]
No worries,

Another good thought about limiting size of items, ill have a think about how best to do this.

**Comment by bensladden** [comment]
Released these features in latest version

**Comment by KBOE2** [comment]
Works great. Thank you so much! :+1:
