### ISSUE TITLE
dlayouts model doesnt change

### ISSUE THREAD

**Issue by cetintozkoparan** [bensladden/vue-responsive-dash#123]
I have to get dlayout model to save, however there is no change in dlayout model after resize or move objects. By the way, if I change to debug mode, I can show changes as json. How to get dlayout model?

**Comment by bensladden** [comment]
Make sure you are using the .sync modifier as per examples:
`
<dashboard :id="'dashExample'">
      <dash-layout v-for="layout in dlayouts" v-bind="layout" :debug="true" :key="layout.breakpoint">
        <dash-item v-for="item in layout.items" v-bind.sync="item" :key="item.id">
          <div class="content"></div>
        </dash-item>
      </dash-layout>
    </dashboard>
`

See item.sync in the above code

**Comment by bensladden** [comment]
Closing for now. I can open again if there is are more questions
