### ISSUE TITLE
Touch events are not working in on my Android phone

### ISSUE THREAD

**Issue by rostamiani** [bensladden/vue-responsive-dash#125]
Hi
I just opened the main page in on phone and dragging is not working.
I tested with Firefox Mobile (Chrome and Opera had time out error!)

**Comment by bensladden** [comment]
Hi, Yes you are correct about touch events. I currently have not implemented this as it creates issues when trying to scroll on mobile devices. only mouse events are currently implemented.

**Comment by rostamiani** [comment]
You can enable dragging when the user long touched. It seems to be the expected behavior.
I think that you can use Pressure.js library to simulate this.

**Comment by bensladden** [comment]
Thankyou for your thoughts, I have enabled touch events on the touch branch of this project. Thanks for the link regarding pressure.js ill have a read when i get a moment.

**Comment by bensladden** [comment]
FYI ive started some testing of another drag/resize lib:
Initial testing is here: [https://github.com/bensladden/vue-interact](https://github.com/bensladden/vue-interact) & [https://vue-interact-test.netlify.app/](https://vue-interact-test.netlify.app/)
See what you think.

**Comment by bensladden** [comment]
Version .4 now used interactjs. moveHold and resizeHold props enable you to delay moving/resizing thus allowing scrolling behavour
