### ISSUE TITLE
Information on purpose & vision for vue-responsive-dash

### ISSUE THREAD

**Issue by tmiquel** [bensladden/vue-responsive-dash#129]
Hi, 

I am unsure this is the right way to ask.

I have been tasked with updating an app which relies on vue-grid-layout.

We are puzzled by the decrease in activity / support witnessed on vue-grid-layout,  and wondering whether it would make sense to make the effort to move to vue-responsive-dash, which looks great.

Hence our question: is there a place where you wrote why you decided to start this repo, and how you think it will evolve. I haven't been able to find an answer on the doc.

Thanks a lot, great work, Thib

**Comment by bensladden** [comment]
Hi Thib,
Thanks for your question. Like you i have implemented vue-grid-layout in some projects. I felt the responsive integration and switching between layouts to be a bit flaky at times (It was added quite late into the codebase) and hence I decided to give it a try myself. 

As far as how it will evolve the key part im looking into currently when able is finding a better way in  integrating mobile devices with dragging and resizing (#125) . I initially chose displace.js as it was a very small codebase (i was trying to limit the package size) and worked quite well with mouse actions. However i am starting to think that using interactjs is going to be the way forward especially as it provides options such choosing what event should start dragging/resizing: 
[https://github.com/taye/interact.js/pull/124](https://github.com/taye/interact.js/pull/124)
and delays:
[https://interactjs.io/docs/faq/#start-action-after-hold](https://interactjs.io/docs/faq/#start-action-after-hold) 
The author has also just recently made the code tree-shakable so i can remove the parts of the lib that i dont need: [https://github.com/taye/interact.js/issues/800](https://github.com/taye/interact.js/issues/800) (Gestures etc) and hopefully keep the package size down.
After that my main focus in integrating other libs that would typically go on dashboards as seen here: https://vue-responsive-dash-vuetify.netlify.app/#/EpicSpinners (early stages)

Hope this helps,

**Comment by bensladden** [comment]
FYI ive started some testing interactjs lib:
Initial testing is here: https://github.com/bensladden/vue-interact & https://vue-interact-test.netlify.app/

**Comment by thibaut-loftorbital** [comment]
Sorry for the delay, but thanks a lot for your reply. Thib (another account)
