### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by leosteets** [bensladden/vue-responsive-dash#135]
Hi guys, I loved your framework, really easy to use, but when I tried using on mobile or simulating mobile with chrome devtools it just doesn't work.

You guys are working on it? Because it's really a deal breaker now a days.

**Comment by bensladden** [comment]
Hi,
Yes see issue #125 basically waiting on interactjs to finalise treeshaking. Currently there are warnings in the console when using this feature which are not desirable.

**Comment by leosteets** [comment]
Nice. Hope this will be available soon.
