### ISSUE TITLE
Grid not readjusting when changing items

### ISSUE THREAD

**Issue by leosteets** [bensladden/vue-responsive-dash#136]
When I remove items from the grid the layout seems to adjust it self, but when I put the item back it stays the same, but if I start dragging any item it just reajust it self and fits perfectly. 

There is a way to force the grid to reajust it self? 

Like a refresh, so I can trigger in my watch event?

Cheers, nice work on the lib.

**Comment by bensladden** [comment]
When placing the item back is it using the same original id?

**Comment by leosteets** [comment]
I changed the ID and it worked perfectly thanks.

**Comment by Cactusx09** [comment]
If you have a time it's could be amazing to add some refresh function. Now hack with id changing this is the only way to do it?
```vue.js
this.newNote.id = -1
this.$nextTick(() => {
   this.newNote.id = 0
})
