### ISSUE TITLE
Autoplacing DashItems

### ISSUE THREAD

**Issue by leosteets** [bensladden/vue-responsive-dash#137]
I was wondering if there is a way to not pass the X and Y for the DashItem and the DashLayout should compute where it should be placed.

In my application I have several cards with diferente sizes and the user can add and remove them dynamicaly, If I could just append it to the "items" it would be awesome, in addition it would solve the problem for different breakpoints/"viewports sizes".

**Comment by bensladden** [comment]
Hi unfortunately not however if you put a large x number in it will compact
it up assuming this is added after the initial load.

**Comment by leosteets** [comment]
I end up creating the logic myself, it only with for height 1 with is fine for now. The currentNumbersOfCols take in consideration the current breakingpoint.

```javascript    
{
    visibleItems(layout) {
      const filteredItems = layout.items.filter(l => l.visible);
      return this.putItemsInTheRightPlace(filteredItems);
    },
    putItemsInTheRightPlace(items) {
      let x = 0;
      let y = 0;
      return items.map(item => {
        // height cannot be bigger than one (or auto placement wont work properly)
        if (item.height > 1) {
          item.height = 1;
        }

        //width cannot be bigger than the layout it self
        if (item.width > this.currentNumbersOfCols) {
          item.width = this.currentNumbersOfCols;
        }

        const spaceOccupiedByThisBlockBreaksLayout = x + item.width > this.currentNumbersOfCols;
        if (spaceOccupiedByThisBlockBreaksLayout) {
          x = 0;
          y++;
        }

        item.x = x;
        item.y = y;

        x += item.width;

        return item;
      });
    }
}
```

This way I dont have to pass the X and Y of my items.

Thank you anyway.
