### ISSUE TITLE
Vue component definition causing duplicate vue instances

### ISSUE THREAD

**Issue by milewski** [bensladden/vue-responsive-dash#179]
I'm not sure why I can't seen to get this component to work ... coping and pasting the example results in a nothingness .. inspecting the  layout instance I noticed that is due to the breaking point always being null:

![image](https://user-images.githubusercontent.com/2874967/87213676-22b4c780-c359-11ea-9b3e-6f514c1c38e0.png)

How is this breakpoint calculate and why it is null?

**Comment by bensladden** [comment]
I need a repo to be able to help. Refer to this: [https://vue-responsive-dash.netlify.app/examples/#green](https://vue-responsive-dash.netlify.app/examples/#green)

**Comment by milewski** [comment]
I had copied and pasted that entire example and still the same... 

```
data() {
            return {
                dlayouts: [
                    {
                        breakpoint: "xl", //changing this to "" empty somewhat shows some data related to the debug.. but the breakpoint is still an empty string... i have no idea why
                        numberOfCols: 12,
                        breakpointWidth: Infinity, // tried 0, 1000000, -Infinity, Infinity all the same
                        items: [
                            {
                                id: "1",
                                x: 0,
                                y: 0,
                                width: 1,
                                height: 1
                            },
                            { id: "2", x: 1, y: 0, width: 2, height: 1 },
                            { id: "3", x: 0, y: 1, width: 2, height: 1 },
                            { id: "4", x: 3, y: 0, width: 2, height: 2 },
                            { id: "5", x: 5, y: 0, width: 1, height: 2 },
                            { id: "6", x: 6, y: 0, width: 2, height: 1 },
                            { id: "7", x: 7, y: 1, width: 5, height: 1 }
                        ]
                    }
                ]
            };
        }
```

It's a bit hard to create a reproducible repo... as I'm trying to use this using https://nova.laravel.com/ which is not that simple to "setup" ... if you are not familiar with it... however, the only thing I can assume could be influencing is the use of tailwind and some global CSS that are set by default with the framework.. for instance, `.item and .content` are already existing css classes... but this still doesnt explain why internally the currentBreakpointValue is "" ... how is the breakpoint be defined? what are the default values of sm/md/xl etc... ?

**Comment by milewski** [comment]
Looks like the problem is in here:

https://github.com/bensladden/vue-responsive-dash/blob/94bbbfcf72b1abefcb61ce8eae7faacb5cdca797/src/components/DashLayout.vue#L107

this.$dashboard is always undefined

**Comment by milewski** [comment]
I made a quickly test and yeah for some reason the inject is not working at all, here is what I did:

As Dashboard component provides a $dashboard value... i tried to retrieve it from child component and it doesnt work:


```js
<template>

    <div id="app">

        <Dashboard id="dashExample">
            <Test/>
        </Dashboard>

    </div>

</template>
```

Test.vue

```js
<script>
    export default {
        inject: { $dashboard: { default: null } },
        mounted() {
            console.log(this.$dashboard) // null
        }
    }
</script>
```

**Comment by bensladden** [comment]
Can you try making your own component and then use provide/inject. As you are using Vue 2.6+ i cant see why this does not work. The only other thing i can think of is the created hook is not firing. If your server has SSR this could be the reason.  In nuxt for example i use <client-only> .... </client-only> wrapping around the dashboard and in vue press i needed to use the following: [https://github.com/bensladden/vue-responsive-dash/blob/master/docs/.vuepress/components/Example.vue](https://github.com/bensladden/vue-responsive-dash/blob/master/docs/.vuepress/components/Example.vue)

**Comment by milewski** [comment]
Well, nova is "SSR" but it uses the template compiler .. that means it returns raw <vue-component-tag> which then Vue compile those tags on the client-side .. so it is not similar of what nuxt does for example... which compiles the component server-side and send out the final compiled HTML..

I just tried doing provide/inject on my own components it it does work:

```vue
<template>

    <Dashboard id="dashExample">
        <Test/>
    </Dashboard>

</template>

<script>

    import { Dashboard, DashItem, DashLayout } from 'vue-responsive-dash'
    import Test from './Test'

    export default {
        name: 'App',
        components: {
            Dashboard,
            DashLayout,
            DashItem,
            Test
        },
        provide: {
            foo: 'Hello world'
        }
    }

</script>

```

```vue
<template>
    <div></div>
</template>

<script>

    export default {
        inject: {
            foo: { default: null },
            $dashboard: { default: 'test' }
        },
        mounted() {
            console.log(this.$dashboard) // test
            console.log(this.foo) // Hello world
        }
    }

</script>
```

![image](https://user-images.githubusercontent.com/2874967/87244352-2f2b4400-c46f-11ea-9e4e-0cf7879f5910.png)

**Comment by bensladden** [comment]
try your `console.log(this.$dashboard())`

i,e, `console.log(this.$dashboard())`

See reason for this implementation here: [https://github.com/vuejs/vue/issues/7017#issuecomment-480906691](https://github.com/vuejs/vue/issues/7017#issuecomment-480906691)

**Comment by bensladden** [comment]
Sorry what i mean i can you try this implementation to see if there is a issue and check if its reactive

**Comment by milewski** [comment]
Well I come to the conclusion that the problem is with the way Laravel nova thought out how their plugin system would work... Essentially what is happening is that when I require this package it imports vuejs and Laravel nova also imports vuejs.. So I ended having 2 versions of vuejs on the page.. Even thou they are the same version I think the inject / provide doesn't work cross vue instances...

That's just my guess...

**Comment by milewski** [comment]
I think the problem can be fixed by removing this import here https://github.com/bensladden/vue-responsive-dash/blob/master/src/components/index.js#L14 I will try it out later

**Comment by bensladden** [comment]
Interesting problem!
I have actually been thinking i should update this particular script to be more like this:
[https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html#What-does-my-packaged-component-look-like](https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html#What-does-my-packaged-component-look-like)
or this:
[https://github.com/Akryum/vue-mention/blob/master/packages/vue-mention/src/index.js](https://github.com/Akryum/vue-mention/blob/master/packages/vue-mention/src/index.js) to give some dynamic naming but not got around to it

**Comment by milewski** [comment]
Hi @bensladden 

Confirmed, removing this: 

![image](https://user-images.githubusercontent.com/2874967/87367857-b16e5200-c5ae-11ea-8bb7-ffacbb6cfb07.png)

Avoid the vue to be bundled with my package.. and the same test above works as expected:


![image](https://user-images.githubusercontent.com/2874967/87367818-98fe3780-c5ae-11ea-888c-6137f9ea5fa4.png)

**Comment by bensladden** [comment]
Good to see can you confirm if the following works?

```js
import DashItem from "./DashItem.vue";
import DashLayout from "./DashLayout.vue";
import Dashboard from "./Dashboard.vue";

const VueResponsiveDash = {
  DashItem,
  DashLayout,
  Dashboard,
};

// Declare install function executed by Vue.use()
export function install(Vue) {
  if (install.installed) return;
  install.installed = true;
  Object.keys(VueResponsiveDash).forEach((name) => {
    Vue.component(name, VueResponsiveDash[name]);
  });
}

// Create module definition for Vue.use()
const plugin = {
  install,
};

// Auto-install when vue is found (eg. in browser via <script> tag)
let GlobalVue = null;
if (typeof window !== "undefined") {
  GlobalVue = window.Vue;
} else if (typeof global !== "undefined") {
  GlobalVue = global.Vue;
}
if (GlobalVue) {
  GlobalVue.use(plugin);
}

export default VueResponsiveDash;
export { DashItem, DashLayout, Dashboard };
```

**Comment by milewski** [comment]
Just tried it works!

**Comment by bensladden** [comment]
Just published the code above, hopefully it all works as expected
