### ISSUE TITLE
Lock Dash Item coordinates

### ISSUE THREAD

**Issue by milewski** [bensladden/vue-responsive-dash#196]
Hey it is easy or possible to add a feature to avoid one DashItem from moving out of this position if the `draggable, resizable` is set to false?

For example I may have something like this:

```vue
<dash-item id=1 draggable=false resizable=false/>
<dash-item id=2 draggable=true resizable=true/>
```

When I drag the item 2 to the place of item 1, the item one shifts its position to the next available slot...  Ideally, I would like the item 1 to always stay at the given coordinates 0,0 and not allow item 2 to ever be on its place.. does it make sense?

**Comment by bensladden** [comment]
Hi, yep makes sense. I wondering however if it's better to create a prop called static or similar rather than using the others. Thoughts?

**Comment by milewski** [comment]
Yeah, I think having a `static` prop would mean that item can not be dragged nor resized, and perhaps compact option would also need to be disabled? as when it is enabled it tries to remove empty slots

**Comment by bensladden** [comment]
Update: I've created a new prop called locked. (see lockedItem branch)
I think it has the desired behavior but ive not had much chance to test it under various layouts.
Would be interested in your feedback.

**Comment by milewski** [comment]
Nice! Thanks I will have a look, by the way I'm using your package to build this other package which I have just released recently: https://github.com/dcasia/nova-dashboard

**Comment by bensladden** [comment]
Nice work looks good let me know how the test goes

**Comment by bensladden** [comment]
Release in v0.5
