### ISSUE TITLE
Scrollbars and selects does not work inside dash items

### ISSUE THREAD

**Issue by albrtogarcia** [bensladden/vue-responsive-dash#198]
Hi! I'm trying to put responsive tables with scrollbars and selects to choose what columns to display inside dash items but the drag event in items overrides the normal function of scrollbars and select elements make them unusable.

Thanks for your code, looks great!

**Comment by bensladden** [comment]
Hi can you confirm if event. stopPropagation() on ur button fixes the issue also check if dragAllowFrom prop assists in defining a custom Draggable area. See docs for more info on this.

**Comment by bensladden** [comment]
Added dragIgnoreProp also now so this should allow the functionality required for the above issues. Closing for now.
