### ISSUE TITLE
Allow setting ignoreFrom on DashItem's interactiveInstance attribute

### ISSUE THREAD

**Issue by herrera8614** [bensladden/vue-responsive-dash#218]
In the scenario of having an interactive item (a chart with drag to see more values, etc.) this package should have a way to disable those elements to trigger a drag on DragItem component.

The same you have for dragAllowFrom, you should have a dragIgnoreFrom prop that will set the ignoreFrom on the interactiveInstance initialization options.

**Comment by bensladden** [comment]
Completed in v0.5
