### ISSUE TITLE
Doesn't appear to work on Windows

### ISSUE THREAD

**Issue by opeik** [bensladden/vue-responsive-dash#41]
Hi, this project is exactly what I was looking for, but unfortunately your demo bugs out completely on my Windows machine. I've tried both Firefox and Chrome. It works perfectly on my Mac though.

**Comment by bensladden** [comment]
Hi, Interesting as ive been developing this on a windows PC. I assume you are referring to the dragging events. I have only been developing using chrome thusfar. Ill did to a quick patch on an error for clearData() as firefox does not like this in the drag end event. However i have noticed its not dragging the event as desired. Ill have to do some more investigation

**Comment by opeik** [comment]
Hi, thanks for the reply! Yes, it's the dragging which goes haywire. Here's a video of the bug: https://streamable.com/nw45k

**Comment by bensladden** [comment]
Wow impressive! Does the same problem happen in firefox aswell or are they different.

**Comment by opeik** [comment]
Same behaviour, out of curiosity I made sure I had the latest stable version of Chrome and tried again. Instead of the panels going nuts they didn't move at all when you dragged them.

**Comment by bensladden** [comment]
Ok, ive started testing two drag libs:
`https://github.com/catc/displace`
`https://interactjs.io/docs/`

Ill see which integrates easiest. Not sure on eta at this point

**Comment by bensladden** [comment]
Ok the latest version now has dragging done by displace. works ok for me on both chrome and firefox. Left me know what you find. Note resize is not updated yet.

**Comment by bensladden** [comment]
resize updated. Let me know how you find it

**Comment by opeik** [comment]
Works great! Seems like you've fixed it.

**Comment by opeik** [comment]
The dragging works as intended now! On the demo page you can drag things over the text elements however, seemingly outside of the grid boundaries.

**Comment by opeik** [comment]
<img width="1551" alt="Screen Shot 2020-01-21 at 18 58 37" src="https://user-images.githubusercontent.com/11566773/72799382-0ffde780-3c80-11ea-9a5b-899f43b402bb.png">

**Comment by bensladden** [comment]
Hi, Yes i had noticed that aswell ill look into it

**Comment by bensladden** [comment]
should be fixed now.

**Comment by opeik** [comment]
Seems to work, thanks very much!

**Comment by bensladden** [comment]
No worries im going to close this issue. If you find anything else let me know
