### ISSUE TITLE
Buggy when using quickly

### ISSUE THREAD

**Issue by TheBraveBunny** [bensladden/vue-responsive-dash#61]
When I try to drag and drop quickly, the layout can often get to where two items overlap or the red item shows when I am not clicking anymore.

Examples:
![image](https://user-images.githubusercontent.com/8333959/74801220-d32b0d80-528a-11ea-8ddd-d6d091548c35.png)
![image](https://user-images.githubusercontent.com/8333959/74801271-f0f87280-528a-11ea-94a6-a196faded445.png)

**Comment by bensladden** [comment]
Thanks for point out the issue. I believe i have now resolved it in v0.3.12 so give it a try and let me know!

**Comment by TheBraveBunny** [comment]
That seems much better! Thank you!
