### ISSUE TITLE
Trying to stack two dashboards on top of each other causes each item to be drawn on top of each other

### ISSUE THREAD

**Issue by TheBraveBunny** [bensladden/vue-responsive-dash#63]
I want to allow users to create new items in the spaces that there is no item already. I want to fill the empty spaces with items that let you create a panel there, like so:

![image](https://user-images.githubusercontent.com/8333959/74902510-2371a080-535b-11ea-8625-a1f9d28fe883.png)

The green panels would be draggable and resizable, but the gray ones would not be. Since adding gray items to the item array causes the green items to go crazy when trying to move them, I think the best way of doing this would be to draw two dashboards, the green one on top and the gray one on bottom. However, using position: absolute and setting the z-index on the layouts cause each item to be drawn on top of each other and each item becomes huge.

position: relative
![image](https://user-images.githubusercontent.com/8333959/74902876-3a64c280-535c-11ea-8122-161adfcfb912.png)

position: absolute
![image](https://user-images.githubusercontent.com/8333959/74902901-4e102900-535c-11ea-9bf7-c0edb0b5e6a4.png)

Is there anything going on in the code that would be messed up by using position: absolute? Is there any way you can see to accomplish what I'm trying to do?

**Comment by bensladden** [comment]
Its always possible! I think there is a simpler way of going about this. I have attached a example here:
[https://codesandbox.io/s/vue-responsive-dash-tbhut](https://codesandbox.io/s/vue-responsive-dash-tbhut)
This code makes some grey squares that do not interact with the green. All that would be left to do is create a computed property that looks at the layout and finds out if a green square exists or not.

Hope it helps!

**Comment by TheBraveBunny** [comment]
This is great! Thank you so much!

**Comment by TheBraveBunny** [comment]
There were some error messages in the sample code you sent saying "Error in directive displace componentUpdated hook: "TypeError: Cannot read property 'opts' of undefined"". I spent some time trying to figure out what's going on, but I'm not sure why it's happening. Could you take a look?

**Comment by bensladden** [comment]
Can you clarify when the error occurs. Is it while your editing? I cannot replicate

**Comment by TheBraveBunny** [comment]
In the CodeSandbox example you made, I drag the left box over to be on top of the right one, and this happens:

![image](https://user-images.githubusercontent.com/8333959/74994222-5458e080-5402-11ea-8127-0e9f01d99b1a.png)

When implementing in my project, I get the same error any time the green panel is set.

![image](https://user-images.githubusercontent.com/8333959/74994317-9a15a900-5402-11ea-9415-1c92ea58fd8c.png)

**Comment by bensladden** [comment]
I've added a check to vue-displace for this error. v0.3.15

**Comment by TheBraveBunny** [comment]
Fixed! Thanks!
