### ISSUE TITLE
Request: a prop that specifies if we want to have the items fall to the top if there isn't anything above it

### ISSUE THREAD

**Issue by TheBraveBunny** [bensladden/vue-responsive-dash#66]
I would like to be able to add a panel without it rising to the top. 

Example:
![image](https://user-images.githubusercontent.com/8333959/74974419-11831280-53da-11ea-9c04-b1f8216bb112.png)

I got this by setting draggable and resizable to false, but once I can move them, the item rises to the top.

**Comment by TheBraveBunny** [comment]
I'm not as familiar with typescript, but I'm thinking this could just be a boolean that checks before running the compact/compactItem methods in Layout.model.ts

So something like this:
In the constructor: `useCompactedGrid?: boolean;`
In the compact method: `if (useCompactedGrid) return items;`
Or something like that...

**Comment by bensladden** [comment]
I've added compact prop in dash-layout. This when false will stop the items moving upwards to fill in the gaps (v0.3.13)

**Comment by TheBraveBunny** [comment]
Awesome! Thank you so much!
