### ISSUE TITLE
How to include components in the DashItems

### ISSUE THREAD

**Issue by bscbrn** [bensladden/vue-responsive-dash#76]
Hello bensladden,
I am very interested in this component. However I cannot find any example of how to render some simple user-defined components inside the dash-item component.
It is mentioned that this shall be done using scope but I think some examples with a one or two simple user-defined components like a static text or an SVG icon could be very helpfull.
I am interested in understanding how a user component can be istantiated multiple times in different dash-items, having different sets of props in each istance and having this stored in data.

Thank you

**Comment by bensladden** [comment]
Hi,
Basic example here:
[https://codesandbox.io/s/vue-responsive-dash-idttk](https://codesandbox.io/s/vue-responsive-dash-idttk)
basically you can add props to your own components in the default slot. You can also inject the item object from inside your component if you perfer to limit the amount of props.
What you may need is a "masterItem" component that uses the item Id and then renders the correct child component using with the content from another data source. (vuex store or another array of render items)

Hope it makes sense.

**Comment by bscbrn** [comment]
Thank you,
this surely helps.
I will elaborate on the provided example.
I suggest you to link the example in the how to use section of the documentation and may be go a few steps forward with a more complex example.

Thank you,
good job.
