### ISSUE TITLE
Edit Mode Functionality 

### ISSUE THREAD

**Issue by PatrikKozak** [bensladden/vue-responsive-dash#83]
Hi @bensladden, is there a way to implement an edit mode functionality to this? Where by clicking a button, I can decide if the containers can be moved or resized and if it's in a viewing state, then I can't move or resize them?

**Comment by bensladden** [comment]
Hi @PatrikKozak of course:

just bind "draggable" and "resizable" to this variable.

`
        <Dash-Item
          v-for="item in layout.items"
          :resizable="editMode"
          :draggable="editMode"
        >
          ...
        </Dash-Item>
`
