### ISSUE TITLE
How to change the space between items

### ISSUE THREAD

**Issue by bscbrn** [bensladden/vue-responsive-dash#86]
Hello,
is there any possibility to change the space between items.
For a specific application I would like to have the items to touch each other with no space in between.
I have seen that there is a 'margin' prop in the Dashboard but is seems not used.

Thank you very much.

**Comment by bensladden** [comment]
Please try the most recent version. Note it is a prop of Dashlayout not Dashboard

**Comment by bensladden** [comment]
v0.3.23

**Comment by bscbrn** [comment]
Thank you bensladden,
it works very well.

Great job!
