### ISSUE TITLE
How to hook a click, dblclick or contextmenu event to a dash-Item component?

### ISSUE THREAD

**Issue by bscbrn** [bensladden/vue-responsive-dash#88]
Hello bensladden,
thank you very much for your continued effort in developing such a nice module.

I am trying to fire a dblclick event so that a configuration window opens up when the user double clicks on a dash-item.
So far I had no luck.
Is there any example I can use?
I am also trying to fire a click or a contextmenu event but nothink happens either.

Thank you very much for any help.

**Comment by bensladden** [comment]
Hi @bscbrn,
Here is an example of dbclick and contextmenu click: [https://codesandbox.io/s/vue-responsive-dash-xnenx](https://codesandbox.io/s/vue-responsive-dash-xnenx). Note the .native is required as it is a component not a div See: [https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components)

**Comment by bscbrn** [comment]
Hi @bensladden,
thank you very much this works very well.
