### ISSUE TITLE
Swapping Layouts moving dash-item

### ISSUE THREAD

**Issue by peterjslater** [bensladden/vue-responsive-dash#90]
Hi

I have a problem with dynamically swapping between layouts, and have recreated the issue here

[https://codesandbox.io/s/vue-responsive-dash-bvrwi](https://codesandbox.io/s/vue-responsive-dash-bvrwi)

When you click the swap button it just swaps between two predefined layouts, however after you click swap twice all the boxes are moved to the bottom of the page, but they should be at the top like when it was first loaded.

I have found that the y positions are getting changed from the v-bind.sync="item" - an update:y is getting emitted for some reason and changing the layout.

This is critical to my project, hope you can find the issue.

Thanks
Peter

**Comment by peterjslater** [comment]
Further update, I just found that it is caused because the id 1 is used in both layouts. If I change the id on the second layout to 5 it seems ok, so when swapping layouts, it seems it is incorrectly  "remembering" the id from the previous layout.

**Comment by bensladden** [comment]
Hi @peterjslater,

This error is most likely down to how vue insert's/removes components during a single cycle. As the id is used in both layouts i can see the potential for corruption. See solution below which takes advantage of the nextTick [https://vuejs.org/v2/api/#mounted](https://vuejs.org/v2/api/#mounted). Note i am clearing the layouts waiting for next tick and then changing to the new desired layouts. Thus giving vue time to remove the components (and therefore the dash items) before re-inserting them

[https://codesandbox.io/s/vue-responsive-dash-3zorp](https://codesandbox.io/s/vue-responsive-dash-3zorp)
