### ISSUE TITLE
Programmatically adding a Dash Item at the bottom of layout

### ISSUE THREAD

**Issue by bscbrn** [bensladden/vue-responsive-dash#91]
Hi @bensladden,
in my application user has a button to add a new Item to a Layout.
The Layout is configured with compact:false so that the Items can be moved in the desired position and they stay there.
At the moment when the user adds a new Item this is created with x:0 and y:0 and pushed into the items list.
This works well but all other Items get moved when user adds and moves the new Item around.

I am wondering what is the best way to calculate the new Item x,y properties so that the new Item is located at the bottom of the layout. Let's say at x:0 but with a y such that it appears just below the last Item already present.

Is there any Layout property that could be exported? Something like Layout.maxheight that could give the actual maximum used height?

Or the only way is to scan the items list and find out the maximum y+height among all Items?

Thank you for any insight.

**Comment by bensladden** [comment]
Unfortunately not, here is the internal code that you could use in a computed var:
`calculateHeight() {
    let maxY = 0;
    let bottomY = 0;
    for (let item of this._dashItems) {
      bottomY = item.y + item.height;
      if (bottomY > maxY) {
        maxY = bottomY;
      }
    }
    return maxY * (this.rowHeight + this.margin.y) + this.margin.y;
  }`

**Comment by bensladden** [comment]
Sorry you just need maxY in the above code.

**Comment by bscbrn** [comment]
Ok, thank you
