### ISSUE TITLE
How to make Dash Items overlap

### ISSUE THREAD

**Issue by bscbrn** [bensladden/vue-responsive-dash#92]
Hi @bensladden,
for a specific application I would like to have the Dash Items overlappable.

User will be able to add new Items in the Layout and draw and resize them freely even if they are colliding with other Items.
Is there any way to disable the collision detection so that other Items are not moved around when the new Item is added/moved/resized?

Thank you

**Comment by bensladden** [comment]
Interesting use case If you were to copy dashItem.vue and not add it to layout (i.e. comment out line "this.layout.addDashItem(this.item);" then in theory yes. Hopfully it is that simple

**Comment by bscbrn** [comment]
I am sorry, I am not sure I got you.
Could you please explain a little bit more?

Thank you

**Comment by bensladden** [comment]
Create you own DashItem.vue copying the code in this lib (you will need the ts file aswell.) and just comment out the line which adds it to layout. It is the layouts job to check collisions so if its never added to the layout it wont check it for collisions.

**Comment by bscbrn** [comment]
Thank you,
understood.
However I am not using the .vue file but I am including the js script in my HTML file as follows:
<script src=\"/resources/vue-responsive-dash.umd.min.js\"></script>
and then
Vue.use('vue-responsive-dash');
in my .js file.

Are there any chance to have a not minimized .js file in the dist folder so that I can make the suggested hack?

I am sorry but I am not very expert.

**Comment by bensladden** [comment]
I'm assuming you don't have typescript in your project judging from the info above so what i recommended wont work. Unfortunately i don't have an easy solution for this. I also think that overlapping dashitems is problematic when trying to resize-drag anyway. Do you need to resize/drag the overlapping items? If not maybe this will help: [https://github.com/bensladden/vue-responsive-dash/issues/63](https://github.com/bensladden/vue-responsive-dash/issues/63) where we created dash items in the spare spaces.
